export const themes = {
  default: {
    '--km-highlight-block': '#fff4c2',
    '--km-highlight-entity': '#b9d7f5',
    '--km-highlight-relation': '#b9d7f5',
    '--km-highlight-selected': '#f4a6a6',
    '--km-highlight-evidence': '#d9cef7',
    '--km-highlight-text': '#26364a',
    '--km-highlight-border': '#8fb5df',
    '--km-draft-bg': '#fff6e5',
    '--km-draft-border': '#e4b66b',
    '--km-draft-text': '#8a5a18',
    '--km-file-mark-bg': '#e7f5ef',
    '--km-file-mark-text': '#42745f',
    '--km-blockquote-border': '#7aa889',
    '--km-inline-code-bg': '#eef1f4',
    '--km-inline-code-text': '#9b5267',
    '--km-code-bg': '#2f363b',
    '--km-code-text': '#edf2f4',
    '--km-assistant-avatar': '#5d8b71',
    '--km-on-primary': '#ffffff',
    '--km-popover-bg': '#ffffff',
    '--km-popover-border': '#dfe5e9',
    '--km-theme-preview-bg': '#ffffff'
  },
  dark: {
    '--el-bg-color': '#20262b',
    '--el-bg-color-page': '#171c20',
    '--el-text-color-primary': '#e5ecef',
    '--el-text-color-regular': '#c1ccd1',
    '--el-text-color-secondary': '#94a3aa',
    '--el-text-color-placeholder': '#718089',
    '--el-select-input-text-color': '#e5ecef',
    '--el-select-option-selected-text-color': '#e5ecef',
    '--el-select-option-hover-background': '#2c363c',
    '--el-border-color': '#3c484f',
    '--el-border-color-light': '#354149',
    '--el-border-color-lighter': '#2d373d',
    '--el-border-color-dark': '#53616a',
    '--el-fill-color-light': '#283238',
    '--el-fill-color-lighter': '#222b30',
    '--el-fill-color-dark': '#313c43',
    '--el-fill-color-darker': '#3a474e',
    '--el-color-primary': '#82a9c6',
    '--el-color-primary-light-3': '#6f91aa',
    '--el-color-primary-light-5': '#5c7b91',
    '--el-color-primary-light-7': '#455d6d',
    '--el-color-primary-light-8': '#354852',
    '--el-color-primary-light-9': '#29373f',
    '--el-color-primary-dark-2': '#a6c5d9',
    '--el-color-success': '#86b59b',
    '--el-color-warning': '#d5b27b',
    '--el-color-danger': '#d99191',
    '--el-color-info': '#91a4ad',
    '--el-mask-color': 'rgba(8, 12, 15, 0.72)',
    '--el-disabled-bg-color': '#293136',
    '--el-disabled-text-color': '#6f7b82',
    '--el-button-disabled-text-color': '#87939a',
    '--el-button-disabled-bg-color': '#2b3338',
    '--el-button-disabled-border-color': '#3b464c',
    '--el-button-hover-text-color': '#d8e7ef',
    '--el-button-hover-bg-color': '#303b42',
    '--el-button-hover-border-color': '#82a9c6',
    '--km-highlight-block': '#635b3d',
    '--km-highlight-entity': '#345676',
    '--km-highlight-relation': '#345676',
    '--km-highlight-selected': '#87545a',
    '--km-highlight-evidence': '#514873',
    '--km-highlight-text': '#edf4f6',
    '--km-highlight-border': '#6e9bc0',
    '--km-draft-bg': '#4d4230',
    '--km-draft-border': '#a98652',
    '--km-draft-text': '#ead19b',
    '--km-file-mark-bg': '#29433c',
    '--km-file-mark-text': '#a4d0ba',
    '--km-blockquote-border': '#78aa8c',
    '--km-inline-code-bg': '#303a40',
    '--km-inline-code-text': '#e3a4b2',
    '--km-code-bg': '#171d21',
    '--km-code-text': '#dce7ea',
    '--km-assistant-avatar': '#67947b',
    '--km-on-primary': '#17232a',
    '--km-popover-bg': '#242d32',
    '--km-popover-border': '#3d4a51',
    '--km-theme-preview-bg': '#20262b'
  },
  blue: {
    '--el-bg-color': '#f7f9fc',
    '--el-bg-color-page': '#edf2f7',
    '--el-text-color-primary': '#2f3d4d',
    '--el-text-color-regular': '#526274',
    '--el-text-color-secondary': '#748395',
    '--el-text-color-placeholder': '#9aa8b5',
    '--el-border-color': '#d4dee8',
    '--el-border-color-light': '#dce5ed',
    '--el-border-color-lighter': '#e6edf3',
    '--el-border-color-dark': '#bccbd8',
    '--el-fill-color-light': '#edf3f8',
    '--el-fill-color-lighter': '#f7f9fc',
    '--el-fill-color-dark': '#e2ebf2',
    '--el-fill-color-darker': '#d6e2eb',
    '--el-color-primary': '#668baa',
    '--el-color-primary-light-3': '#7fa1bb',
    '--el-color-primary-light-5': '#9ab6c9',
    '--el-color-primary-light-7': '#bfd1df',
    '--el-color-primary-light-8': '#d4e1ea',
    '--el-color-primary-light-9': '#e7eff5',
    '--el-color-primary-dark-2': '#4d718f',
    '--el-color-success': '#719d87',
    '--el-color-warning': '#bd9760',
    '--el-color-danger': '#c87979',
    '--el-color-info': '#8294a4',
    '--km-highlight-block': '#fff1c9',
    '--km-highlight-entity': '#c6ddf2',
    '--km-highlight-relation': '#c6ddf2',
    '--km-highlight-selected': '#f2b4b4',
    '--km-highlight-evidence': '#ddd3f2',
    '--km-highlight-text': '#2f4051',
    '--km-highlight-border': '#8eabc2',
    '--km-draft-bg': '#fff5df',
    '--km-draft-border': '#d6ad6d',
    '--km-draft-text': '#80591f',
    '--km-file-mark-bg': '#e3edf5',
    '--km-file-mark-text': '#557998',
    '--km-blockquote-border': '#789bb6',
    '--km-inline-code-bg': '#e9eef3',
    '--km-inline-code-text': '#a15d73',
    '--km-code-bg': '#35424e',
    '--km-code-text': '#edf3f7',
    '--km-assistant-avatar': '#668ca7',
    '--km-on-primary': '#ffffff',
    '--km-popover-bg': '#f8fafc',
    '--km-popover-border': '#d8e2eb',
    '--km-theme-preview-bg': '#f7f9fc'
  },
  green: {
    '--el-bg-color': '#f7faf5',
    '--el-bg-color-page': '#eef4eb',
    '--el-text-color-primary': '#35463b',
    '--el-text-color-regular': '#536458',
    '--el-text-color-secondary': '#77877b',
    '--el-text-color-placeholder': '#a0aea2',
    '--el-border-color': '#d5e1d4',
    '--el-border-color-light': '#dce7da',
    '--el-border-color-lighter': '#e7eee5',
    '--el-border-color-dark': '#becfbd',
    '--el-fill-color-light': '#edf4eb',
    '--el-fill-color-lighter': '#f7faf5',
    '--el-fill-color-dark': '#e1ecdf',
    '--el-fill-color-darker': '#d5e5d2',
    '--el-color-primary': '#6d9277',
    '--el-color-primary-light-3': '#82a68a',
    '--el-color-primary-light-5': '#9cbaa1',
    '--el-color-primary-light-7': '#bfd3c0',
    '--el-color-primary-light-8': '#d4e3d3',
    '--el-color-primary-light-9': '#e8f0e6',
    '--el-color-primary-dark-2': '#567a61',
    '--el-color-success': '#769b7a',
    '--el-color-warning': '#b89563',
    '--el-color-danger': '#c47d7d',
    '--el-color-info': '#819186',
    '--chat-user-bubble-bg': '#dceadb',
    '--chat-user-bubble-text': '#35463b',
    '--chat-assistant-bubble-bg': '#eef4eb',
    '--chat-assistant-bubble-text': '#35463b',
    '--km-highlight-block': '#f5edc9',
    '--km-highlight-entity': '#c9e0d0',
    '--km-highlight-relation': '#c9e0d0',
    '--km-highlight-selected': '#efb7b1',
    '--km-highlight-evidence': '#d9d1e9',
    '--km-highlight-text': '#35463b',
    '--km-highlight-border': '#8eae96',
    '--km-draft-bg': '#f8efdb',
    '--km-draft-border': '#c7a86c',
    '--km-draft-text': '#765522',
    '--km-file-mark-bg': '#e5f0e5',
    '--km-file-mark-text': '#557b60',
    '--km-blockquote-border': '#7da287',
    '--km-inline-code-bg': '#eaf1e8',
    '--km-inline-code-text': '#916070',
    '--km-code-bg': '#344239',
    '--km-code-text': '#eef5ed',
    '--km-assistant-avatar': '#709779',
    '--km-on-primary': '#ffffff',
    '--km-popover-bg': '#f8fbf6',
    '--km-popover-border': '#d5e2d2',
    '--km-theme-preview-bg': '#f7faf5'
  }
};

export const applyTheme = (theme) => {
  const root = document.documentElement;
  
  // 清除所有主题相关的样式
  Object.keys(themes).forEach(themeName => {
    root.classList.remove(`theme-${themeName}`);
  });
  
  // Remove the complete union so switching themes cannot leave stale values.
  const themeKeys = new Set(Object.values(themes).flatMap(theme => Object.keys(theme)));
  themeKeys.forEach(key => root.style.removeProperty(key));
  Object.entries(themes[theme] || {}).forEach(([key, value]) => root.style.setProperty(key, value));
  
  // 设置当前主题的 class
  root.setAttribute('data-theme', theme);
};
